# Generated by Django 3.2 on 2021-07-31 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210731_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='url_field',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
