# Generated by Django 3.2 on 2021-07-31 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_menu_url_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='logo',
            field=models.ImageField(blank=True, upload_to='logo'),
        ),
    ]
