# Generated by Django 3.2 on 2021-07-31 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_menu_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, upload_to='logo')),
            ],
        ),
        migrations.RemoveField(
            model_name='menu',
            name='logo',
        ),
        migrations.AlterField(
            model_name='menu',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
